### ISSUE TITLE
Object 'notes'not found

### ISSUE THREAD

**Issue by erkinacar5** [andrewGhazi/mpradesigntools#2]
Hello Andrew,

It might be something I am doing wrong but I cannot get the mpradesigntools working on my CentOS 7 server with R version 3.5.3. I did a clean installing of every related package written in the installation part but here is how things go for me:

`> library(mpradesigntools)
> result <- processVCF(vcf="/data/storage/erkin/Susette/new_vcf7.vcf", nper=14, upstreamContextRange=75, downstreamContextRange=75, fwprimer="ACTGGCCAG", revprimer="CTCGGCGGCC")
[1] "Filtering barcode set to ensure that all barcodes contain all four barcodes..."
[1] "Removed 0 barcodes out of 1140292 (0%)"
[1] "Filtering undesired barcode patterns..."
[1] "Removed 5622 barcodes from the usable pool out of the original 1140292 (0.493%)"
[1] "Processing SNPs..."
|======================================================|100% ~0 s remaining     Error in .f(.x[[i]], ...) : object 'notes' not found
In addition: Warning message:
\`cols\` is now required.
Please use \`cols = c(seqs)\`
`

I am attaching the VCF file I created for this (I changed it to .txt to be able to upload it). I am thinking maybe the VCF format is not good, since I manually created it, but I find it interesting that it processes all the SNPs then just cannot get the notes object. It may also be my lack of R knowledge, if that's the case sorry in advance!

Thank you for checking this!
Erkin

[new_vcf7.txt](https://github.com/andrewGhazi/mpradesigntools/files/3905569/new_vcf7.txt)

**Comment by andrewGhazi** [comment]
Glancing over your VCF I see nothing obviously wrong. I'm fairly certain this problem was due to an update in the tidyr package that I hadn't addressed yet. Try it now.

**Comment by andrewGhazi** [comment]
After fixing another bug, I got around to testing your provided dataset and was able to get it to run with no problems.
